#!/bin/bash

set -euo pipefail

SOURCE_DIR=${SOURCE_LOG_DIR:-"/tmp/logs"}
BACKUP_DIR=${BACKUP_LOG_DIR:-"/tmp/logs/archive"}
LOG_FILE=${WARDEN_LOG:-"./warden_activity.log"}
DISK_THRESHOLD=${DISK_THRESHOLD:-80}

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

CONFIG_FILE="$SCRIPT_DIR/warden.conf"
if [[ -f "$CONFIG_FILE" ]]; then
    source "$CONFIG_FILE"
else
    echo -e "Warning: Config file not found at $CONFIG_FILE. Using defaults."
fi

source "$SCRIPT_DIR/system_state.sh"
source "$SCRIPT_DIR/user_audit.sh"
source "$SCRIPT_DIR/archive_logs.sh"


RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' 



show_help() {
    echo "Usage: ./warden.sh [OPTION]"
    echo ""
    echo "Options:"
    echo "  --report    Display system health (CPU, Mem, Disk)"
    echo "  --cleanup   Archive logs older than 7 days"
    echo "  --all       Run all checks and cleanup"
    echo "  -h, --help  Display this help message"
}

log() {
    echo -e "${GREEN}[$(date  '+%Y-%m-%d %H:%M:%S')] $* ${NC}"
}


system_report() {
    log "System state report"
    get_memory
    get_disk_usage
    get_top_processes
}


if [[ $# -eq 0 ]]; then
    show_help
    exit 1
fi

case "$1" in
    --report) 
        system_report
        log "System Report generated by $USER" >> "$LOG_FILE"
        ;;
    --cleanup) 
        log_cleanup
        log "Log Archiving by $USER" >> "$LOG_FILE"
        ;;
    --useraudit) 
        user_audit
        log "User Auditing by $USER" >> "$LOG_FILE"
        ;;
    --all) 
        system_report 
        user_audit
        log_cleanup 
        log "System Report, Log Archiving and User Auditing by $USER" >> "$LOG_FILE"
        ;;
    *)
        echo -e "${RED}Error: Invalid option '$1'${NC}"
        show_help
        exit 1
        ;;
esac

echo -e "\n${GREEN}Task completed successfully at $(date)${NC}"